### ISSUE TITLE
Migrate codebase or change ownership to seawatts/ember-smiple-auth-auth0

### ISSUE THREAD

**Issue by seawatts** [auth0-community/auth0-ember-simple-auth#57]
Hey, I have been working on my own Auth0 Ember addon here: https://github.com/seawatts/ember-simple-auth-auth0

It would be nice to unify them or, if you want, put them under the auth0 GitHub organization. 

Thoughts?

**Comment by chenkie** [comment]
Hey thanks @seawatts. We're in the process of migrating things over to a new auth0-community org where community members can put in Auth0 integrations, samples etc. If you're interested, it would be perfect for that. wdyt?

**Comment by seawatts** [comment]
Hey @chenkie yeah I am definitely willing to help! Let me know how we should coordinate this. 😄

**Comment by chenkie** [comment]
Thanks @seawatts. Can you send me an email? ryan.chenkie@auth0.com.

**Comment by cs3b** [comment]
what can I do to help you guys? (as this is pretty important) @seawatts addon works much better then this one. 
I also prefere @seawatts name for the package, as we add auth0 to ember-simple-auth (not other way around)

**Comment by chenkie** [comment]
Thanks @cs3b. We're actually working on a refresh to this repo right now. We should have it done within the next week or two.

**Comment by snewcomer** [comment]
@chenkie any update to this refresh?

**Comment by chenkie** [comment]
hey @snewcomer, the updated plugin from @seawatts has been moved [here](https://github.com/auth0-community/ember-simple-auth-auth0). I'll close this out now as this fork will be deprecated.

**Comment by XaserAcheron** [comment]
Congrats @seawatts for the promotion of sorts! And thanks for keeping this alive n' up to date, of course.
